-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgm06v0XnALBxkKGHE
E1T0KqbORGe7BH2TRPcRIKGanJegCgYIKoZIzj0DAQehRANCAATrHomK4kpWcuSB
M8zDPO9wHpFkQcKTizcuM/PRnJNMNjqI6n2yC2tzKhEH3dzX4nubRzZPqPKFwQxx
0zXAc8Ws
-----END PRIVATE KEY-----